#version: '3.1'
#
#services:
#
#  db:
#    image: dailyreport
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      MYSQL_USERNAME: root
#      MYSQL_PASSWORD: ozlam2002
#      MYSQL_DB: crm
version: '3.5'
services:
   redis:
     image: redis:latest
     ports:
      - "6379:6379"

   app:
     build:
      context:  .
      dockerfile: Dockerfile
     ports:
       - "8080:8080"
     depends_on:
       - redis

     #   dailyreport_service_provider:
#    container_name: crm
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/crm
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=ozlam2002
#    ports:
#      - "8080:8080"
##    restart: unless-stopped
#    depends_on:
#      - db
#  db:
#    image: mysql:latest
#    container_name: mysql_provider_crm
#    ports:
#      - "3305:3306"
##    restart: unless-stopped
#    environment:
#      - MYSQL_DATABASE=mysql
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=ozlam2002
#      - MYSQL_ROOT_PASSWORD=ozlam2002
